In [2]:
from numpy import array, tanh, dot, random

In [11]:
class NeuralNetwork():

  def __init__(self):
    random.seed(1)
    self.weight_matrix = random.random((3,1))

  def tanh(self, x):
    return tanh(x)

  def tanh_derivative(self, x):
    return 1-tanh(x)**2

  def forward_propagation(self, input_matrix):
    return tanh(dot(input_matrix, self.weight_matrix))

  def train(self, train_inputs, train_outputs, iterations):
    for iteration in range(iterations):
      output = self.forward_propagation(train_inputs)

      error = output - train_outputs
      adjustment = dot(train_inputs.T, error*self.tanh_derivative(output))
      self.weight_matrix += adjustment

if __name__ == "__main__":
  neural_network = NeuralNetwork()
  print("Random wrights at the start of the training")
  print(neural_network.weight_matrix)

  train_inputs = array([[0,0,1],[1,1,1],[1,0,1],[0,1,1]])
  train_outputs = array([[0,1,1,0]]).T
  neural_network.train(train_inputs, train_outputs, 1000)

  print("New weights after the training")
  print(neural_network.weight_matrix)

  print("Testing model on unseen data")
  print(neural_network.forward_propagation([1,0,0]))

Random wrights at the start of the training
[[4.17022005e-01]
 [7.20324493e-01]
 [1.14374817e-04]]
New weights after the training
[[-1678.28947899]
 [-1256.07433021]
 [-2516.12109725]]
Testing model on unseen data
[-1.]


In [4]:
random.random((3,1))

array([[0.69548139],
       [0.79025413],
       [0.17511946]])